[package]
name = "migrations_macros"
version = "1.4.2"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
license = "MIT OR Apache-2.0"
description = "Codegeneration macros for diesels embedded migrations"
homepage = "http://diesel.rs"

[dependencies]
migrations_internals = { path = "../migrations_internals" }
syn = { version = "1", features = ["extra-traits"] }
quote = "1"
proc-macro2 = "1"

[dev-dependencies]
tempdir = "0.3.4"

[lib]
proc-macro = true

[features]
default = []
